In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [54]:
# read in the raw data from the github url

df = pd.read_csv("https://raw.githubusercontent.com/suneel0101/lesson-plan/master/crunchbase_monthly_export.csv")

In [55]:
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN

#### 1. Clean the data. Use .apply and lambda functions where you can

In [57]:
# rename the columns to remove spaces and extra characters
df.columns = ['permalink','name','homepage_url', 'category_list', 'market', 'funding_total_usd', 'status', 'country_code', 'state_code', 'region', 'city', 'funding_rounds', 'founded_at', 'founded_month','founded_quarter','founded_year','first_funding_at', 'last_funding_at','undefined']
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,undefined
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN

In [16]:
df.describe()

       funding_rounds  founded_year  undefined
count    44950.000000  35226.000000        0.0
mean         1.681135   2007.083461        NaN
std          1.269198      7.522161        NaN
min          1.000000   1900.000000        NaN
25%          1.000000           NaN        NaN
50%          1.000000           NaN        NaN
75%          2.000000           NaN        NaN
max         16.000000   2014.000000        NaN

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44950 entries, 0 to 44949
Data columns (total 19 columns):
permalink            44950 non-null object
name                 44949 non-null object
homepage_url         41914 non-null object
category_list        40997 non-null object
market               40997 non-null object
funding_total_usd    0 non-null float64
status               42208 non-null object
country_code         40805 non-null object
state_code           27773 non-null object
region               39615 non-null object
city                 40109 non-null object
funding_rounds       44950 non-null int64
founded_at           35292 non-null object
founded_month        35226 non-null object
founded_quarter      35226 non-null object
founded_year         35226 non-null float64
first_funding_at     44950 non-null object
last_funding_at      44950 non-null object
undefined            0 non-null float64
dtypes: float64(3), int64(1), object(15)
memory usage: 6.5+ MB

In [21]:
df.get_dtype_counts()

float64     2
int64       1
object     16
dtype: int64

In [33]:
df.columns

Index([u'permalink', u'name', u'homepage_url', u'category_list', u'market',
       u'funding_total_usd', u'status', u'country_code', u'state_code',
       u'region', u'city', u'funding_rounds', u'founded_at', u'founded_month',
       u'founded_quarter', u'founded_year', u'first_funding_at',
       u'last_funding_at', u'undefined'],
      dtype='object')

In [79]:
# convert the funding, year founded, and funding_rounds columns to integers
#df['funding_total_usd'] = df.funding_total_usd.str.replace(',','')
#df['funding_total_usd'] = df['funding_total_usd'].astype('int')
#df['funding_total_usd'] = df.apply(lambda x: int(x))
#df.funding_total_usd = df.funding_total_usd.map(int)
#df['funding_total_usd'] = df['funding_total_usd'].apply(lambda x: int(x) if str.isdigit(x) else np.nan)
df['funding_total_usd'] = df.funding_total_usd.str.replace('-',np.nan)

#print (df[ pd.to_numeric(df['funding_total_usd'], errors='coerce').isnull()])

In [78]:
df.head(400)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,undefined
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,750000,NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,1750000,acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,4000000,operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,40000,operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,1500000,operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN
5,/organization/n-plusn,#NAME?,http://plusn.com,|Software|,Software,600000,operating,USA,NY,New York City,New York,1,1/1/12,2012-01,2012-Q1,2012.0,8/29/12,8/29/12,NaN
6,/organization/club-domains,.Club Domains,http://nic.club/,|Software|,Software,7000000,NaN,USA,FL,Ft. Lauderdale,Oakland Park,1,10/10/11,2011-10,2011-Q4,2011.0,5/31/13,5/31/13,NaN
7,/organization/fox-networks,.Fox Networks,http://www.dotfox.com,|Advertising|,Advertising,4912393,closed,ARG,NaN,Buenos Aires,Buenos Aires,1,NaN,NaN,NaN,NaN,1/16/07,1/16/07,NaN
8,/organization/0-6-com,0-6.com,http://www.0-6.com,|Curated Web|,Curated Web,2000000,operating,NaN,NaN,NaN,NaN,1,1/1/07,2007-01,2007-Q1,2007.0,3/19/08,3/19/08,NaN
9,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,|Software|,Software,np.nan,operating,USA,IL,"Springfield, Illinois",Champaign,1,1/1/10,2010-01,2010-Q1,2010.0,7/24/14,7/24/14,NaN
10,/organization/0xdata,0xdata,http://www.0xdata.com,|Analytics|,Analytics,1700000,operating,USA,CA,SF Bay Area,Mountain View,1,1/1/11,2011-01,2011-Q1,2011.0,1/3/13,1/3/13,NaN
11,/organization/1-2-3-listo,"1,2,3 Listo",http://www.123listo.com,|E-Commerce|,E-Commerce,40000,operating,CHL,NaN,Santiago,Las Condes,1,1/1/12,2012-01,2012-Q1,2012.0,2/18/13,2/18/13,NaN
12,/organization/1-4-all,1-4 All,NaN,|Entertainment|Games|Software|,Entertainment,np.nan,operating,USA,NC,North Carolina,Connellys Springs,1,NaN,NaN,NaN,NaN,4/21/13,4/21/13,NaN
13,/organization/1-800-dentist,1-800-DENTIST,http://www.1800dentist.com,|Health and Wellness|,Health and Wellness,np.nan,operating,USA,CA,Los Angeles,Los Angeles,1,1/1/86,1986-01,1986-Q1,1986.0,8/19/10,8/19/10,NaN
14,/organization/1-800-doctors,1-800-DOCTORS,http://1800doctors.com,|Health and Wellness|,Health and Wellness,1750000,operating,USA,NJ,Newark,Iselin,1,1/1/84,1984-01,1984-Q1,1984.0,3/2/11,3/2/11,NaN
15,/organization/1-618-technology,1.618 Technology,NaN,|Real Estate|,Real Estate,np.nan,operating,USA,FL,Orlando,Orlando,1,12/7/13,2013-12,2013-Q4,2013.0,1/22/14,1/22/14,NaN
16,/organization/10-20-media,10-20 Media,http://www.10-20media.com,|E-Commerce|,E-Commerce,2050000,operating,USA,MD,Baltimore,Woodbine,4,1/1/01,2001-01,2001-Q1,2001.0,6/18/09,12/28/11,NaN
17,/organization/1000-corks,1000 Corks,http://1000corks.com,|Search|,Search,40000,operating,USA,OR,"Portland, Oregon",Lake Oswego,1,1/1/08,2008-01,2008-Q1,2008.0,8/23/11,8/23/11,NaN
18,/organization/1000-markets,1000 Markets,http://www.1000markets.com,|Marketplaces|Art|E-Commerce|,Art,500000,acquired,NaN,NaN,NaN,NaN,1,1/1/09,2009-01,2009-Q1,2009.0,5/15/09,5/15/09,NaN
19,/organization/1000jobboersen-de,1000jobboersen.de,http://www.1000jobboersen.de,|Curated Web|,Curated Web,np.nan,operating,DEU,NaN,Berlin,Berlin,1,NaN,NaN,NaN,NaN,9/16/11,9/16/11,NaN
20,/organization/1000memories,1000memories,http://1000memories.com,|Curated Web|,Curated Web,2535000,acquired,USA,CA,SF Bay Area,San Francisco,2,7/1/10,2010-07,2010-Q3,2010.0,1/1/10,2/16/11,NaN
21,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,|Curated Web|,Curated Web,4462651,operating,USA,WA,Seattle,Bellevue,4,1/1/08,2008-01,2008-Q1,2008.0,10/14/09,1/15/14,NaN
22,/organization/1001-menus,1001 Menus,http://1001menus.com,|Local Businesses|Restaurants|,Local Businesses,1869079,operating,FRA,NaN,Paris,Paris,2,11/20/10,2010-11,2010-Q4,2010.0,12/27/12,11/13/13,NaN
23,/organization/1006-tv,1006.tv,http://www.1006.tv/,|Media|Games|,Games,10000000,operating,NaN,NaN,Beijing,Beijing,3,1/1/09,2009-01,2009-Q1,2009.0,1/1/11,7/31/14,NaN
24,/organization/100du-tv,100du.tv,http://www.100du.com,|Hospitality|,Hospitality,3000000,operating,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1/7/08,8/13/10,NaN
25,/organization/100e-com,100e.com,http://www.100e.com,|Education|,Education,3000000,operating,CHN,NaN,Beijing,Beijing,1,NaN,NaN,NaN,NaN,1/1/06,1/1/06,NaN
26,/organization/100plus,100Plus,http://www.100plus.com,|Analytics|,Analytics,1250000,acquired,USA,CA,SF Bay Area,San Francisco,2,9/16/11,2011-09,2011-Q3,2011.0,11/2/11,11/30/11,NaN
27,/organization/1010data,1010data,http://www.1010data.com,|Software|,Software,35000000,operating,USA,NY,New York City,New York,1,1/1/00,2000-01,2000-Q1,2000.0,3/8/10,3/8/10,NaN
28,/organization/10bestthings,10BestThings,http://10bestthings.com,|Curated Web|,Curated Web,50000,closed,USA,OH,Cleveland,Cleveland,1,4/1/09,2009-04,2009-Q2,2009.0,4/1/09,4/1/09,NaN
29,/organization/10sec,10sec,https://10s.ec/,|Social Commerce|E-Commerce|Mobile Commerce|,E-Commerce,1600000,NaN,NaN,NaN,NaN,NaN,1,7/8/13,2013-07,2013-Q3,2013.0,5/8/14,5/8/14,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,/organization/8hands,8hands,http://www.8hands.com,|Messaging|Social Media|Public Relations|,Messaging,1500000,closed,ISR,NaN,Asia,NaN,2,NaN,NaN,NaN,NaN,1/1/08,1/1/08,NaN
371,/organization/8minutenergy-renewables,8minutenergy Renewables,http://8minutenergy.com,|Clean Technology|,Clean Technology,30000000,operating,USA,CA,Sacramento,Folsom,1,NaN,NaN,NaN,NaN,6/17/14,6/17/14,NaN
372,/organization/8th-story,8th Story,http://www.8thstory.com,|Lifestyle|Retail|E-Commerce|Fashion|,E-Commerce,np.nan,operating,USA,CA,Los Angeles,Los Angeles,1,1/1/13,2013-01,2013-Q1,2013.0,8/1/13,8/1/13,NaN
373,/organization/alvenda-inc,8thBridge,http://www.8thbridge.com,|Social Commerce|E-Commerce|,E-Commerce,15590000,acquired,USA,MN,Minneapolis,Minneapolis,3,11/1/08,2008-11,2008-Q4,2008.0,11/16/09,3/21/11,NaN
374,/organization/8tracks,8tracks Radio,http://www.8tracks.com,|Music|,Music,1200000,NaN,USA,CA,SF Bay Area,San Francisco,1,8/8/08,2008-08,2008-Q3,2008.0,10/1/11,10/1/11,NaN
375,/organization/8trip,8Trip,http://8trip.cn,|Travel|,Travel,24600000,operating,CHN,NaN,Shanghai,Suzhou,1,1/1/11,2011-01,2011-Q1,2011.0,11/13/13,11/13/13,NaN
376,/organization/8villages,8villages,http://www.8villages.com,|Mobile|,Mobile,150000,operating,SGP,NaN,Singapore,Singapore,1,6/1/11,2011-06,2011-Q2,2011.0,12/1/13,12/1/13,NaN
377,/organization/8x8-inc,8x8 Inc,http://www.8x8.com,|Telecommunications|Web Hosting|,Telecommunications,30608728,acquired,USA,CA,SF Bay Area,San Jose,1,1/1/87,1987-01,1987-Q1,1987.0,10/3/11,10/3/11,NaN
378,/organization/908-devices,908 Devices,http://908devices.com,|Manufacturing|,Manufacturing,15100000,operating,USA,MA,Boston,Boston,2,1/1/12,2012-01,2012-Q1,2012.0,9/5/12,8/27/13,NaN
379,/organization/90sec-technologies,90sec Technologies,http://www.90sec.me,|Television|Weddings|Consumer Electronics|Mobi...,Apps,100000,operating,ISR,NaN,Tel Aviv,Tel Aviv,1,6/30/13,2013-06,2013-Q2,2013.0,9/1/13,9/1/13,NaN
380,/organization/91-boyuan-wireles,91 Boyuan Wireles,http://dev.91.com,|Mobile|,Mobile,20000000,operating,CHN,NaN,Fuzhou Shi,Fuzhou Shi,1,NaN,NaN,NaN,NaN,12/1/11,12/1/11,NaN
381,/organization/91-golf,91 Golf,http://www.91golf.com,|Mobile|,Mobile,317460,operating,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1/1/12,1/1/12,NaN
382,/organization/91-wireless,91 Wireless,http://www.91.com,|Mobile|,Mobile,30000000,acquired,CHN,NaN,Fuzhou Shi,Fuzhou Shi,1,9/1/10,2010-09,2010-Q3,2010.0,12/1/11,12/1/11,NaN
383,/organization/911-pets,911 Pets,http://911pets.us/,NaN,NaN,np.nan,operating,USA,TX,Dallas,Dallas,1,12/28/13,2013-12,2013-Q4,2013.0,12/28/13,12/28/13,NaN
384,/organization/9158-julur-com,9158 Julur.com,http://www.9158.com/,|Social Media|,Social Media,4502251,operating,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,12/1/10,12/1/10,NaN
385,/organization/91datong-com,91datong.com,http://www.91datong.com/,|Finance|,Finance,63590263,operating,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,3/1/11,3/1/11,NaN
386,/organization/91jinrong,91JinRong,http://91jinrong.com,|Finance|Curated Web|,Curated Web,19790000,operating,CHN,NaN,Beijing,Beijing,3,NaN,NaN,NaN,NaN,10/1/11,6/16/14,NaN
387,/organization/99-fahrenheit,99 Fahrenheit,NaN,|Finance|,Finance,1380700,NaN,ITA,NaN,Milan,Milano,1,10/1/11,2011-10,2011-Q4,2011.0,10/15/11,10/15/11,NaN
388,/organization/99-co,99.co,http://www.99.co,|Local Businesses|,Local Businesses,560000,operating,SGP,NaN,Singapore,NaN,1,NaN,NaN,NaN,NaN,5/6/14,5/6/14,NaN
389,/organization/99bill,99Bill,http://www.99bill.com,|Payments|E-Commerce|,E-Commerce,81574271,operating,CHN,NaN,Shanghai,Shanghai,4,1/1/05,2005-01,2005-Q1,2005.0,4/26/06,12/19/12,NaN
390,/organization/99degrees-custom,99degrees Custom,http://www.99degreescustom.com,NaN,NaN,100000,operating,USA,MA,Boston,Lawrence,1,NaN,NaN,NaN,NaN,10/30/13,10/30/13,NaN
391,/organization/99designs,99designs,http://99designs.com,|Marketplaces|Online Shopping|Crowdsourcing|De...,Crowdsourcing,35000000,operating,USA,CA,SF Bay Area,San Francisco,1,2/1/08,2008-02,2008-Q1,2008.0,4/28/11,4/28/11,NaN
392,/organization/99dresses,99dresses,http://99dresses.com,|File Sharing|Fashion|,Fashion,105651,operating,AUS,NaN,Sydney,Sydney,2,1/1/10,2010-01,2010-Q1,2010.0,3/30/12,6/1/12,NaN
393,/organization/99inn-cc,99inn.cc,http://www.99inn.cc/,|Automotive|,Automotive,75000000,operating,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,8/1/12,8/1/12,NaN
394,/organization/99presents,99Presents,http://www.99presents.com,|Social Commerce|E-Commerce|,E-Commerce,20000,operating,IND,NaN,Vadodara,Vadodara,1,3/20/12,2012-03,2012-Q1,2012.0,9/1/12,9/1/12,NaN
395,/organization/99taojin-com,99taojin.com,http://www.99taojin.com/,|Manufacturing|,Manufacturing,7575757,operating,NaN,NaN,NaN,NaN,1,1/1/09,2009-01,2009-Q1,2009.0,1/1/11,1/1/11,NaN
396,/organization/99tests,99tests,http://99tests.com,|Software|,Software,210000,operating,IND,NaN,Bangalore,Bangalore City,3,2/14/11,2011-02,2011-Q1,2011.0,12/1/10,7/22/13,NaN
397,/organization/99times-cn,99times.cn,http://www.99times.cn,|E-Commerce|,E-Commerce,np.nan,closed,CHN,NaN,Shanghai,Shanghai,1,1/1/05,2005-01,2005-Q1,2005.0,8/23/10,8/23/10,NaN
398,/organization/9car-technology-llc,9car Technology LLC,http://www.chejianghu.com,|Automotive|Cars|E-Commerce|,Automotive,80000,closed,CHN,NaN,Beijing,Beijing,2,11/18/09,2009-11,2009-Q4,2009.0,11/18/09,1/6/10,NaN
399,/organization/9diamond,9DIAMOND,http://info.9diamond.com,|E-Commerce|,E-Commerce,9600000,operating,CHN,NaN,Shanghai,Shanghai,2,3/1/05,2005-03,2005-Q1,2005.0,1/1/05,1/1/08,NaN

In [ ]:
# convert category_list so that each cell is a list of categories

In [ ]:
# use value_counts on market, status, and country_code to check for any repeats or misnamed entries

In [ ]:
# BONUS: convert the date columns to appropriate datetime objects

#### 2. Using isnull(), take a subset of the dataframe that has no founded at date

#### 3. Create a new column, founded_year_x, that's a copy of founded_year. Then, replace all the missing values with either the mean , mode, or median of that column. 
Add a note explaining which statistic you picked and why:

#### 4. Take a subset of US-based companies using boolean selection

#### 5. Create a pivot table showing total, mean, and median funding amount by year

#### 6. Create a pivot table showing total, mean and median funding amount by market

#### 7. CHALLENGE: Using matplotlib, create a scatter plot showing funding amount on the y-axis, and first_funding_date on the x-axis
(first_funding_date will need to be a timestamp)

#### 8. Here's the fun part. Create a hypothesis based on your data that you can reasonably test. 
For example: "Credit companies based in the US that only get 1 round of funding tend to receive more funding than companies based outside the US"



When you have your hypothesis, write it below, and Slack it to the instructors so we can check in.

#### 9. Test your hypothesis. 

You'll need to evaluate your hypothesis using a t-test (see Monday's lecture 1.3), so make sure you have enough data compare samples. If your original hypothesis is too narrow, you may need to broaden the scope.

#### 10. CHALLENGE
- Plot the distribution of both samples
- Explain your results in one short sentence. 
- Explain your result in a slighly longer technical paragraph, touching on the statistics you presented. 
- Subset your findings: if you looked at a certain market in a certain geography, break it down by another variable (e.g number of funding rounds) and compare those samples.