# ![](https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png) Project 3: Liquor Sales + Linear Regression

### Overview
This week we learned we learned how to use scikit-learn to run linear regression models, how Goals & Business Objectives translate to Model Fit, and also how to optimize models using cross-validation. Now we're going to use these skills to dig into a rich set of data!

The state of Iowa provides many data sets on their website, including [this dataset](https://www.dropbox.com/sh/pf5n5sgfgiri3i8/AACkaMeL_i_WgZ00rpxOOcysa?dl=0) which contains transactions for all stores that have a class E liquor license. You can choose one of the following two scenarios.

NOTE: If this dataset is too big for you to run the python code on, feel free to use [this 10% dataset version of Iowa liquor sales](https://drive.google.com/file/d/0Bx2SHQGVqWaseDB4QU9ZSVFDY2M/view?usp=sharing). You may want to use it anyway to test your code since it will be faster.

#### Scenario 1: State tax board

You are a data scientist in residence at the Iowa State tax board. The Iowa State legislature is considering changes in the liquor tax rates and wants a report of current liquor sales by county and projections for the rest of the year.

**Goal for Scenario #1:** Your task is as follows:

* Calculate the yearly liquor sales for each store using the provided data. You can add up the transactions for each year, and store sales in 2015 specifically will be used later as your target variable (it may help to use a groupby or pivot table, since you'll use this table to build your model).
* Use the data from 2015 to make a linear model using as many variables as you find useful to predict the yearly sales of each store. You must use the sales from Jan to March per store as one of your variables.
* Use your model for 2015 to estimate total sales for each store in 2016, extrapolating from the sales so far for Jan-March of 2016.
* Report your findings, including any projected increase or decrease in total sales (over the entire state) for the tax committee of the Iowa legislature.
* Use cross-validation to check how your model predicts to held out data compared to the model metrics on the full dataset.
* _Challenging Bonus_: We did not cover the topics of regularization for linear regression this week, but those feeling bold can try to use and understand regularizing linear regressions. This will require self-guided research/reading and scikit-learn functions that we have not gone over in class! Use cross-validation to tune the regularization parameter that maximizes R^2 on your holdout sets for the Ridge regression and the Lasso Regression. Do the regularized models perform better than the non-regularized model? Which regularized model performs better? What is the Ridge regression doing? What is the Lasso doing.


#### Scenario 2: Market research for new store locations

A liquor store owner in Iowa is looking to expand to new locations and has hired you to investigate the market data for potential new locations. The business owner is interested in the details of the best model you can fit to the data so that his team can evaluate potential locations for a new storefront.

**Goal for Scenario #2:** Your task is to:

* Build models of total sales based on location, price per bottle, total bottles sold. You may find it useful to build models for each county, zip code, or city.
* Provide a table of the best performing stores by location type of your choice (city, county, or zip code) and the predictions of your model(s).
* Based on your models and the table of data, recommend some general locations to the business owner, taking into account model performance. Validate your model's performance and ability to predict future sales using cross-validation.
* _Bonus_: Recommend targets for volume sold and price per bottle!

---

###  Requirements

Using a provided dataset, create a Linear Regression model and an executive summary write up based on your chosen scenario.

Your work must:
**Identify the problem**
- Write a high quality problem statement
- Describe the goals of your study and criteria for success

**Acquire the data**
- Obtain the data [here](https://www.dropbox.com/sh/pf5n5sgfgiri3i8/AACkaMeL_i_WgZ00rpxOOcysa?dl=0) -- it's from [Iowa.gov](Iowa.gov), filtered and reduced a bit
- There is a further reduced version that is 10% of the version above [here](https://drive.google.com/file/d/0Bx2SHQGVqWaseDB4QU9ZSVFDY2M/view?usp=sharing)

**Explore the data**
- Import data using the Pandas Library
- Perform exploratory analysis methods with visualization and statistical analysis
- State the risks and assumptions of your data

**Mine the data**
- Create necessary derived columns from the data
- Format, clean, slice, and combine the data in Python

**Refine the data**
- Determine outliers, skew distribution of important variables (if any)
- Determine correlations / causations in the data
- Validate findings using statistical analysis (p-values, confidence intervals) as applicable

**Build a data model**
- Complete linear regressions using scikit-learn or statsmodels and interpret your findings
- Calculate and plot predicted probabilities and/or present tables of results
- Describe the bias-variance tradeoff of your model and errors metrics
- Evaluate model fit by using loss functions, including mean absolute error, mean squared error, and root mean squared error, or r-squared

**Present the results**
- Create a Jupyter writeup hosted on GitHub that provides a dataset overview with visualizations, statistical analysis, data cleaning methodologies, and models
- Create a writeup on the interpretation of findings including an executive summary with conclusions and next steps

***Bonus!:***
- Handle outliers, use regularization (Ridge & Lasso regressions)
- Brainstorm ways to improve your analysis; for example:
 - Add additional breakdowns and models, e.g. by month.
 - Recommend additional data that might improve your models
 - Can you think of other uses for the dataset? E.g healthcare / disease estimates
- Create a blog post of at least 500 words (and 1-2 graphics!) describing your data, analysis, and approach. Link to it in your Jupyter notebook.
 - **Pro Tip:** Try converting your Jupyter notebook to HTML to create an easy blog post draft!

### Necessary Deliverables / Submission

- Materials must be in a clearly labeled Jupyter notebook that satisfies project requirements:
- Materials must be submitted to your DSI-projects repo via GitHub.
- Materials must be submitted by 9am on the Thursday of week 4 (6/30).

---

### Starter code

The [starter code](./starter-code/) has a loose outline for you to follow to explore the data and build your models. Make sure to consider strategies for your specific scenario. You will also address several of the items in Labs 3.3 and 3.4.


### Dataset

[This dataset](https://www.dropbox.com/sh/pf5n5sgfgiri3i8/AACkaMeL_i_WgZ00rpxOOcysa?dl=0) contains transactions for all stores that have a class E liquor license in the state of Iowa. It has been significantly reduced from the original file but you'll need to reduce and clean it further.

[This dataset](https://drive.google.com/file/d/0Bx2SHQGVqWaseDB4QU9ZSVFDY2M/view?usp=sharing) contains the same information as the data above, but just 10% of the original sample.

> Students interested in viewing the original, unreduced file can compare the reduced Project version with the [original full version, found here](http://marcharper.codes/Iowa_Liquor_Sales-all.zip). In fact, Iowa provides over 2gb of data stretching further back in time!

---

### Suggested Ways to Get Started

**Tips for both scenarios:**
1. Likely you will find it useful to reduce the data set with pandas before fitting models. You may want to make a new table with the following data for each store:
 * The vendor name
 * The location data (zip code, county, city)
 * The total sales for the year
 * The total sales for each month (or at least for Jan-March for the first scenario)
 * The total volume sold
 * The total number of bottles sold
 * The average price per bottle (perhaps useful for distinguishing store types)

2. We're using linear regression for our models. Find the best model you can, but don't fret if you cannot get a really good model. We'll learn techniques later that will help improve your analysis, such as _classifying store types_. For now do the best you can with the tools that you have.

3. Take advantage of pandas as much as possible -- the `groupby`, `summation`, and other features of DataFrames can make computing the necessary summary data much easier. This is a great time to practice what you learned in Week 2!

4. Take care in the presentation of your results. Your audience is likely non-technical, so explain your findings in accessible language.

**General suggestions:**
- Write pseudocode before you write actual code. Thinking through the logic of something helps.  
- Read the docs for whatever technologies you use. Most of the time, there is a tutorial that you can follow, but not always, and learning to read documentation is crucial to your success!
- Document **everything**.  

### Useful Resources
- [Documentation for SKLearn](http://scikit-learn.org/stable/user_guide.html)
- [What is regularization?](https://www.quora.com/What-is-regularization-in-machine-learning)

---

### Project Feedback + Evaluation

[Attached here is a complete rubric for this project.](./project-03-rubric.md)

Your instructors will score each of your technical requirements using the scale below:

    Score | Expectations
    ----- | ------------
    **0** | _Incomplete._
    **1** | _Does not meet expectations._
    **2** | _Meets expectations, good job!_
    **3** | _Exceeds expectations, you wonderful creature, you!_

 This will serve as a helpful overall gauge of whether you met the project goals, but __the more important scores are the individual ones__ above, which can help you identify where to focus your efforts for the next project!

In [17]:
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
import pandas as pd

df = pd.read_csv('/Users/timothyernst/Documents/General Assembly/Iowa_Liquor_Sales_reduced.csv')

/Users/timothyernst/anaconda/envs/Python2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [18]:
df.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,03/31/2016,5029,DAVENPORT,52806,82.0,Scott,1022100.0,TEQUILA,370,87152,Avion Silver,375,$9.99,$14.99,12,$179.88,4.5,1.19
1,03/31/2016,5029,DAVENPORT,52806,82.0,Scott,1022100.0,TEQUILA,395,89197,Jose Cuervo Especial Reposado Tequila,1000,$12.50,$18.75,2,$37.50,2.0,0.53
2,03/31/2016,4959,CEDAR FALLS,50613,7.0,Black Hawk,1071100.0,AMERICAN COCKTAILS,380,63959,Uv Blue Raspberry Lemonade Pet,1750,$5.97,$8.96,6,$53.76,10.5,2.77
3,03/31/2016,2190,DES MOINES,50314,77.0,Polk,1031200.0,VODKA FLAVORED,205,40597,New Amsterdam Red Berry,200,$2.24,$3.36,48,$161.28,9.6,2.54
4,03/31/2016,5240,WEST BRANCH,52358,NaN,NaN,1081200.0,CREAM LIQUEURS,305,73055,Rumchata,750,$12.50,$18.75,6,$112.50,4.5,1.19

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2709552 entries, 0 to 2709551
Data columns (total 18 columns):
Date                     object
Store Number             int64
City                     object
Zip Code                 object
County Number            float64
County                   object
Category                 float64
Category Name            object
Vendor Number            int64
Item Number              int64
Item Description         object
Bottle Volume (ml)       int64
State Bottle Cost        object
State Bottle Retail      object
Bottles Sold             int64
Sale (Dollars)           object
Volume Sold (Liters)     float64
Volume Sold (Gallons)    float64
dtypes: float64(4), int64(5), object(9)
memory usage: 372.1+ MB

In [30]:
col_names = df.columns

In [24]:
df['Store Number'].nunique()

1403

In [32]:
un_items = []
def find_uni(list):
    for x in list:
        print df[x].unique

print find_uni(col_names)

<bound method Series.unique of 0          03/31/2016
1          03/31/2016
2          03/31/2016
3          03/31/2016
4          03/31/2016
5          03/31/2016
6          03/31/2016
7          03/31/2016
8          03/31/2016
9          03/31/2016
10         03/31/2016
11         03/31/2016
12         03/31/2016
13         03/31/2016
14         03/31/2016
15         03/31/2016
16         03/31/2016
17         03/31/2016
18         03/31/2016
19         03/31/2016
20         03/31/2016
21         03/31/2016
22         03/31/2016
23         03/31/2016
24         03/31/2016
25         03/31/2016
26         03/31/2016
27         03/31/2016
28         03/31/2016
29         03/31/2016
              ...
2709522    01/05/2015
2709523    01/05/2015
2709524    01/05/2015
2709525    01/05/2015
2709526    01/05/2015
2709527    01/05/2015
2709528    01/05/2015
2709529    01/05/2015
2709530    01/05/2015
2709531    01/05/2015
2709532    01/05/2015
2709533    01/05/2015
2709534    01/05/2015
2709535    01/05/2015
2709536    01/05/2015
2709537    01/05/2015
2709538    01/05/2015
2709539    01/05/2015
2709540    01/05/2015
2709541    01/05/2015
2709542    01/05/2015
2709543    01/05/2015
2709544    01/05/2015
2709545    01/05/2015
2709546    01/05/2015
2709547    01/05/2015
2709548    01/05/2015
2709549    01/05/2015
2709550    01/05/2015
2709551    01/05/2015
Name: Date, dtype: object>
<bound method Series.unique of 0          5029
1          5029
2          4959
3          2190
4          5240
5          4988
6          3993
7          5029
8          5144
9          5029
10         5029
11         5029
12         5029
13         5029
14         5029
15         5029
16         4447
17         5029
18         5029
19         5029
20         5029
21         5029
22         5029
23         5034
24         5029
25         5029
26         5029
27         5029
28         4802
29         5029
           ...
2709522    2527
2709523    3403
2709524    4267
2709525    4229
2709526    4794
2709527    2560
2709528    2558
2709529    2573
2709530    4188
2709531    2599
2709532    3952
2709533    3631
2709534    3773
2709535    2643
2709536    2633
2709537    2648
2709538    2506
2709539    4164
2709540    4972
2709541    3525
2709542    4000
2709543    2590
2709544    3494
2709545    3907
2709546    2448
2709547    4696
2709548    2590
2709549    3631
2709550    2517
2709551    2643
Name: Store Number, dtype: int64>
<bound method Series.unique of 0                  DAVENPORT
1                  DAVENPORT
2                CEDAR FALLS
3                 DES MOINES
4                WEST BRANCH
5                CEDAR FALLS
6                   WATERLOO
7                  DAVENPORT
8                     ANKENY
9                  DAVENPORT
10                 DAVENPORT
11                 DAVENPORT
12                 DAVENPORT
13                 DAVENPORT
14                 DAVENPORT
15                 DAVENPORT
16                 URBANDALE
17                 DAVENPORT
18                 DAVENPORT
19                 DAVENPORT
20                 DAVENPORT
21                 DAVENPORT
22                 DAVENPORT
23                MASON CITY
24                 DAVENPORT
25                 DAVENPORT
26                 DAVENPORT
27                 DAVENPORT
28                DES MOINES
29                 DAVENPORT
                 ...
2709522           DES MOINES
2709523    COLUMBUS JUNCTION
2709524                ANITA
2709525               HARLAN
2709526           BURLINGTON
2709527               MARION
2709528       MOUNT PLEASANT
2709529            MUSCATINE
2709530           HOLY CROSS
2709531           CORALVILLE
2709532           BETTENDORF
2709533              AUDUBON
2709534         CEDAR RAPIDS
2709535             WATERLOO
2709536           DES MOINES
2709537      WEST DES MOINES
2709538           BURLINGTON
2709539           BETTENDORF
2709540               MONONA
2709541           WASHINGTON
2709542             WOODBINE
2709543         CEDAR RAPIDS
2709544             WATERLOO
2709545            MUSCATINE
2709546            INDIANOLA
2709547      WEST DES MOINES
2709548         CEDAR RAPIDS
2709549              AUDUBON
2709550               NEWTON
2709551             WATERLOO
Name: City, dtype: object>
<bound method Series.unique of 0          52806
1          52806
2          50613
3          50314
4          52358
5          50613
6          50701
7          52806
8          50021
9          52806
10         52806
11         52806
12         52806
13         52806
14         52806
15         52806
16         50322
17         52806
18         52806
19         52806
20         52806
21         52806
22         52806
23         50401
24         52806
25         52806
26         52806
27         52806
28         50310
29         52806
           ...
2709522    50315
2709523    52738
2709524    50020
2709525    51537
2709526    52601
2709527    52302
2709528    52641
2709529    52761
2709530    52053
2709531    52241
2709532    52722
2709533    50025
2709534    52401
2709535    50701
2709536    50320
2709537    50265
2709538    52601
2709539    52722
2709540    52159
2709541    52353
2709542    51579
2709543    52402
2709544    50702
2709545    52761
2709546    50125
2709547    50266
2709548    52402
2709549    50025
2709550    50208
2709551    50701
Name: Zip Code, dtype: object>
<bound method Series.unique of 0          82.0
1          82.0
2           7.0
3          77.0
4           NaN
5           7.0
6           7.0
7          82.0
8          77.0
9          82.0
10         82.0
11         82.0
12         82.0
13         82.0
14         82.0
15         82.0
16         77.0
17         82.0
18         82.0
19         82.0
20         82.0
21         82.0
22         82.0
23         17.0
24         82.0
25         82.0
26         82.0
27         82.0
28         77.0
29         82.0
           ...
2709522    77.0
2709523    58.0
2709524    15.0
2709525    83.0
2709526    29.0
2709527    57.0
2709528    44.0
2709529    70.0
2709530    31.0
2709531    52.0
2709532    82.0
2709533     5.0
2709534    57.0
2709535     7.0
2709536    77.0
2709537    77.0
2709538    29.0
2709539    82.0
2709540    22.0
2709541    92.0
2709542    43.0
2709543    57.0
2709544     7.0
2709545    70.0
2709546    91.0
2709547    77.0
2709548    57.0
2709549     5.0
2709550    50.0
2709551     7.0
Name: County Number, dtype: float64>
<bound method Series.unique of 0                Scott
1                Scott
2           Black Hawk
3                 Polk
4                  NaN
5           Black Hawk
6           Black Hawk
7                Scott
8                 Polk
9                Scott
10               Scott
11               Scott
12               Scott
13               Scott
14               Scott
15               Scott
16                Polk
17               Scott
18               Scott
19               Scott
20               Scott
21               Scott
22               Scott
23         Cerro Gordo
24               Scott
25               Scott
26               Scott
27               Scott
28                Polk
29               Scott
              ...
2709522           Polk
2709523         Louisa
2709524           Cass
2709525         Shelby
2709526     Des Moines
2709527           Linn
2709528          Henry
2709529      Muscatine
2709530        Dubuque
2709531        Johnson
2709532          Scott
2709533        Audubon
2709534           Linn
2709535     Black Hawk
2709536           Polk
2709537           Polk
2709538     Des Moines
2709539          Scott
2709540        Clayton
2709541     Washington
2709542       Harrison
2709543           Linn
2709544     Black Hawk
2709545      Muscatine
2709546         Warren
2709547           Polk
2709548           Linn
2709549        Audubon
2709550         Jasper
2709551     Black Hawk
Name: County, dtype: object>
<bound method Series.unique of 0          1022100.0
1          1022100.0
2          1071100.0
3          1031200.0
4          1081200.0
5          1011200.0
6          1081390.0
7          1022100.0
8          1051010.0
9          1052010.0
10         1022100.0
11         1052010.0
12         1052010.0
13         1012100.0
14         1062310.0
15         1062310.0
16         1031080.0
17         1082900.0
18         1022100.0
19         1011200.0
20         1012100.0
21         1011100.0
22         1012100.0
23         1012100.0
24         1012100.0
25         1032200.0
26         1031080.0
27         1051140.0
28         1012100.0
29         1051010.0
             ...
2709522    1081900.0
2709523    1062310.0
2709524    1081030.0
2709525    1031080.0
2709526    1042100.0
2709527    1081200.0
2709528    1081390.0
2709529    1031200.0
2709530    1051010.0
2709531    1071100.0
2709532    1032200.0
2709533    1031080.0
2709534    1022100.0
2709535    1051010.0
2709536    1082900.0
2709537    1011250.0
2709538    1012100.0
2709539    1011300.0
2709540    1031200.0
2709541    1032200.0
2709542    1081030.0
2709543    1031080.0
2709544    1031080.0
2709545    1062300.0
2709546    1081600.0
2709547    1031200.0
2709548    1012200.0
2709549    1081330.0
2709550    1071100.0
2709551    1012200.0
Name: Category, dtype: float64>
<bound method Series.unique of 0                                     TEQUILA
1                                     TEQUILA
2                          AMERICAN COCKTAILS
3                              VODKA FLAVORED
4                              CREAM LIQUEURS
5                   STRAIGHT BOURBON WHISKIES
6                           IMPORTED SCHNAPPS
7                                     TEQUILA
8                     AMERICAN GRAPE BRANDIES
9                     IMPORTED GRAPE BRANDIES
10                                    TEQUILA
11                    IMPORTED GRAPE BRANDIES
12                    IMPORTED GRAPE BRANDIES
13                          CANADIAN WHISKIES
14                                 SPICED RUM
15                                 SPICED RUM
16                             VODKA 80 PROOF
17         MISC. IMPORTED CORDIALS & LIQUEURS
18                                    TEQUILA
19                  STRAIGHT BOURBON WHISKIES
20                          CANADIAN WHISKIES
21                           BLENDED WHISKIES
22                          CANADIAN WHISKIES
23                          CANADIAN WHISKIES
24                          CANADIAN WHISKIES
25                      IMPORTED VODKA - MISC
26                             VODKA 80 PROOF
27                             PEACH BRANDIES
28                          CANADIAN WHISKIES
29                    AMERICAN GRAPE BRANDIES
                          ...
2709522    MISC. AMERICAN CORDIALS & LIQUEURS
2709523                            SPICED RUM
2709524                       COFFEE LIQUEURS
2709525                        VODKA 80 PROOF
2709526                     IMPORTED DRY GINS
2709527                        CREAM LIQUEURS
2709528                     IMPORTED SCHNAPPS
2709529                        VODKA FLAVORED
2709530               AMERICAN GRAPE BRANDIES
2709531                    AMERICAN COCKTAILS
2709532                 IMPORTED VODKA - MISC
2709533                        VODKA 80 PROOF
2709534                               TEQUILA
2709535               AMERICAN GRAPE BRANDIES
2709536    MISC. IMPORTED CORDIALS & LIQUEURS
2709537        SINGLE BARREL BOURBON WHISKIES
2709538                     CANADIAN WHISKIES
2709539                    TENNESSEE WHISKIES
2709540                        VODKA FLAVORED
2709541                 IMPORTED VODKA - MISC
2709542                       COFFEE LIQUEURS
2709543                        VODKA 80 PROOF
2709544                        VODKA 80 PROOF
2709545                          FLAVORED RUM
2709546                       WHISKEY LIQUEUR
2709547                        VODKA FLAVORED
2709548                       SCOTCH WHISKIES
2709549                        PEACH SCHNAPPS
2709550                    AMERICAN COCKTAILS
2709551                       SCOTCH WHISKIES
Name: Category Name, dtype: object>
<bound method Series.unique of 0          370
1          395
2          380
3          205
4          305
5          260
6          421
7          410
8          259
9          389
10         410
11         420
12         389
13         260
14         260
15         260
16         300
17         192
18         395
19          65
20         260
21         297
22         115
23          55
24         260
25         260
26         380
27         115
28         115
29         205
          ...
2709522    322
2709523    260
2709524     65
2709525    434
2709526     35
2709527    260
2709528    421
2709529    380
2709530     85
2709531    395
2709532    370
2709533    260
2709534    410
2709535    259
2709536    260
2709537     65
2709538     65
2709539     85
2709540    380
2709541    260
2709542    370
2709543    297
2709544     55
2709545     35
2709546     85
2709547    205
2709548    260
2709549     65
2709550    395
2709551    260
Name: Vendor Number, dtype: int64>
<bound method Series.unique of 0          87152
1          89197
2          63959
3          40597
4          73055
5          17090
6          69636
7          88294
8          52318
9          49185
10         88296
11         48105
12         49186
13         11298
14         43337
15         43244
16         36904
17         65256
18         89196
19         19066
20         10805
21         23826
22         11774
23         11936
24         11297
25         64511
26         37346
27         56195
28         11788
29         52594
           ...
2709522    75213
2709523    43337
2709524    67556
2709525    36308
2709526    28236
2709527    68022
2709528    69611
2709529    40244
2709530    52806
2709531    58872
2709532    34029
2709533    37994
2709534    88296
2709535    52317
2709536    66636
2709537    19235
2709538    10628
2709539    86668
2709540    40625
2709541    64727
2709542    67571
2709543    35913
2709544    37938
2709545    43136
2709546    86887
2709547    40192
2709548     5346
2709549    82847
2709550    58868
2709551     5329
Name: Item Number, dtype: int64>
<bound method Series.unique of 0                                        Avion Silver
1               Jose Cuervo Especial Reposado Tequila
2                      Uv Blue Raspberry Lemonade Pet
3                             New Amsterdam Red Berry
4                                            Rumchata
5                                Bulleit Bourbon 10YR
6                  Dr. Mcgillicuddy's Cherry Schnapps
7                               Patron Silver Tequila
8                               Christian Bros Brandy
9                            Remy Martin Vsop (flask)
10                              Patron Tequila Silver
11                                        Hennessy VS
12                            Remy Martin Vsop Cognac
13                        Crown Royal Canadian Whisky
14                          Captain Morgan Spiced Rum
15                Captain Morgan 100 Proof Spiced Rum
16                                Mccormick Vodka Pet
17                               Jagermeister Liqueur
18              Jose Cuervo Especial Reposado Tequila
19                                           Jim Beam
20                            Crown Royal Regal Apple
21                                          Five Star
22                                       Black Velvet
23               Canadian Ltd Whisky Convenience Pack
24                        Crown Royal Canadian Whisky
25                                        Ciroc Apple
26                                     Phillips Vodka
27              Paul Masson Peach Grande Amber Brandy
28                                       Black Velvet
29                                    E & J Vs Brandy
                              ...
2709522                                    Kinky Blue
2709523                     Captain Morgan Spiced Rum
2709524                         Kamora Coffee Liqueur
2709525                                 Hawkeye Vodka
2709526                           Bombay Sapphire Gin
2709527                       Bailey's Salted Caramel
2709528         Dr. Mcgillicuddy's Apple Pie Schnapps
2709529                      Prairie Organic Cucumber
2709530                                 Korbel Brandy
2709531    Jose Cuervo Authentic Light Margarita Lime
2709532                  Absolut Citron (lemon Vodka)
2709533                         Smirnoff Vodka 80 Prf
2709534                         Patron Tequila Silver
2709535                  Christian Bros Brandy-Square
2709536                Romana Sambuca Italian Liquore
2709537              Knob Creek Single Barrel Reserve
2709538                          Canadian Club Whisky
2709539            Jack Daniel's Tennessee Honey Mini
2709540                             UV Chocolate Cake
2709541                                Ciroc Amaretto
2709542                          Kahlua Mocha Liqueur
2709543                            Five O'clock Vodka
2709544                                    Skol Vodka
2709545                                 Bacardi Limon
2709546                              Southern Comfort
2709547                       New Amsterdam Pineapple
2709548                            Johnnie Walker Red
2709549                            Dekuyper Peachtree
2709550    Jose Cuervo Authentic Strawberry Margarita
2709551                           Johnnie Walker Blue
Name: Item Description, dtype: object>
<bound method Series.unique of 0           375
1          1000
2          1750
3           200
4           750
5           750
6           750
7           375
8          1750
9           375
10          750
11          375
12          750
13         1750
14         1000
15          750
16          375
17          750
18          750
19          750
20          375
21          750
22          375
23          750
24         1000
25          375
26          750
27          375
28         1750
29          375
           ...
2709522     375
2709523    1000
2709524     750
2709525    1750
2709526     750
2709527     750
2709528     750
2709529     750
2709530     750
2709531    1750
2709532    1000
2709533     375
2709534     750
2709535    1000
2709536     750
2709537     750
2709538    1750
2709539     500
2709540     750
2709541     750
2709542     750
2709543     200
2709544    1750
2709545     750
2709546    1000
2709547     375
2709548     750
2709549    1000
2709550    1750
2709551     750
Name: Bottle Volume (ml), dtype: int64>
<bound method Series.unique of 0            $9.99
1           $12.50
2            $5.97
3            $2.24
4           $12.50
5           $23.00
6            $8.67
7           $14.00
8           $11.83
9           $10.66
10          $27.00
11           $9.99
12          $21.98
13          $31.99
14          $11.75
15          $10.24
16           $1.80
17          $12.05
18          $10.49
19          $10.49
20           $7.75
21           $3.46
22           $3.07
23           $3.84
24          $18.75
25           $9.25
26           $3.57
27           $3.22
28          $10.45
29           $3.49
            ...
2709522      $5.00
2709523     $11.75
2709524      $6.30
2709525      $7.17
2709526     $11.64
2709527     $13.25
2709528      $8.32
2709529     $11.00
2709530      $5.70
2709531      $8.20
2709532     $14.99
2709533      $4.75
2709534     $27.00
2709535      $7.11
2709536     $13.00
2709537     $24.67
2709538     $15.75
2709539      $9.06
2709540      $6.50
2709541     $19.00
2709542     $10.99
2709543      $1.13
2709544      $7.11
2709545      $8.50
2709546     $12.48
2709547      $3.50
2709548     $14.25
2709549      $7.62
2709550      $8.20
2709551    $130.00
Name: State Bottle Cost, dtype: object>
<bound method Series.unique of 0           $14.99
1           $18.75
2            $8.96
3            $3.36
4           $18.75
5           $34.50
6           $13.01
7           $21.00
8           $17.75
9           $15.99
10          $40.50

In [ ]:

def make_int(col):
    for col in my_columns:
        df[col] = df[col].astype('float64', coerce=True)

In [29]:
df['Category'].unisque()

AttributeError: 'Series' object has no attribute 'unisque'