# ![](https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png) Regression Challenge
Week 3 | Day 5

## The Times university ranking dataset analysis

In this challenge, you will draw on the skills you have learned over the past three weeks to create a model of university prestige using the provided predictors. Specifically, your goal is to **predict the total score for each university for the year 2016**. This score directly maps into the university ranking.

You will be drawing on the following skills:
- Basic python and pandas skills
- Data cleaning
- EDA
- Regression
- Regularization
- Cross validation

## The Dataset

The data is in a csv file in your repo. It contains the following columns:

- **world_rank** - world rank for the university. Contains rank ranges and equal ranks (e.g. = 94 and 201-250).
- **university_name** - name of university.
- **country** - country of each university.
- **teaching** - university score for teaching (the learning environment).
- **international** - university score international outlook (staff, students, research).
- **research** - university score for research (volume, income and reputation).
- **citations** - university score for citations (research influence).
- **income** - university score for industry income (knowledge transfer).
- **total_score** - total score for university, used to determine rank.
- **num_students** - number of students at the university.
- **student_staff_ratio** - Number of students divided by number of staff.
- **international_students** - Percentage of students who are international.
- **female_male_ratio** - Female student to Male student ratio.
- **year** - year of the ranking (2011 to 2016 included).

The target is the **total score**, which directly corresponds to the final ranking.

**N.B. - if the total score is reported as "-" that will be considered a 0 when scoring.**

## Guidelines

- You will be provided with the data and targets from 2011 through 2015 and the data (no targets) for 2016.<br><br>

- Before 12:00pm, all final answers should be submitted by filling in the  predicted values for each university in the submission sheet. (.to_csv() should be useful for this). <br><br>

- Your submission will be assessed on MSE -- so consider your loss functions! <br><br>

## Guidelines

The analysis is up to you. **This is fully open-ended.** You are expected to:

- Load the packages you need to do analysis
- Perform EDA on variables of interest
- Form a hypothesis or hypotheses on what is important for the score
- Check your data for problems, clean and munge data into correct formats
- Create or combine new columns/features where beneficial
- Perform statistical analysis with regression and describe the results

---

I will be here in class to help, but if you do not know how to do something, I expect you to **check documentation first**.

**You are not expected to know how to do things by heart. Knowing how to effectively look up the answers on the internet is a critical skill for data scientists!**

## Teams

Finally, you will be working as part of a team on this. To the randomizer...

In [22]:
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

df = pd.read_csv('/Users/timothyernst/GA-DSI/curriculum/week-03/5.1-regression-challenge/datasets/challenge-dataset.csv')
df

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
0,1,Harvard University,United States of America,99.7,72.4,98.7,98.8,34.5,96.1,"20,152",8.9,25%,NaN,2011
1,2,California Institute of Technology,United States of America,97.7,54.6,98.0,99.9,83.7,96,"2,243",6.9,27%,33 : 67,2011
2,3,Massachusetts Institute of Technology,United States of America,97.8,82.3,91.4,99.9,87.5,95.6,"11,074",9.0,33%,37 : 63,2011
3,4,Stanford University,United States of America,98.3,29.5,98.1,99.2,64.3,94.3,"15,596",7.8,22%,42:58:00,2011
4,5,Princeton University,United States of America,90.9,70.3,95.4,99.9,-,94.2,"7,929",8.4,27%,45:55:00,2011
5,6,University of Cambridge,United Kingdom,90.5,77.7,94.1,94.0,57,91.2,"18,812",11.8,34%,46:54:00,2011
6,6,University of Oxford,United Kingdom,88.2,77.2,93.9,95.1,73.5,91.2,"19,919",11.6,34%,46:54:00,2011
7,8,"University of California, Berkeley",United States of America,84.2,39.6,99.3,97.8,-,91.1,"36,186",16.4,15%,50:50:00,2011
8,9,Imperial College London,United Kingdom,89.2,90,94.5,88.3,92.9,90.6,"15,060",11.7,51%,37 : 63,2011
9,10,Yale University,United States of America,92.1,59.2,89.7,91.5,-,89.5,"11,751",4.4,20%,50:50:00,2011
10,11,"University of California, Los Angeles",United States of America,83.0,48.1,92.9,93.2,-,87.7,"38,206",10.3,15%,52:48:00,2011
11,12,University of Chicago,United States of America,79.1,62.8,87.9,96.9,-,86.9,"14,221",6.9,21%,42:58:00,2011
12,13,Johns Hopkins University,United States of America,80.9,58.5,89.2,92.3,100,86.4,"15,128",3.6,23%,50:50:00,2011
13,14,Cornell University,United States of America,82.2,62.4,88.8,88.1,34.7,83.9,"21,424",10.2,19%,48:52:00,2011
14,15,ETH Zurich � Swiss Federal Institute of Techno...,Switzerland,77.5,93.7,87.8,83.1,-,83.4,"18,178",14.7,37%,31 : 69,2011
15,15,University of Michigan,United States of America,83.9,53.3,89.1,84.1,59.6,83.4,"41,786",9.0,16%,48:52:00,2011
16,17,University of Toronto,Canada,75.8,-,87.9,82.2,-,82,"66,198",19.5,15%,NaN,2011
17,18,Columbia University,United States of America,73.8,90.9,73.8,92.6,-,81,"25,055",5.9,28%,NaN,2011
18,19,University of Pennsylvania,United States of America,71.8,32.9,82.7,93.6,43.7,79.5,"20,376",6.5,20%,51:49:00,2011
19,20,Carnegie Mellon University,United States of America,70.3,39.1,79.3,95.7,53.7,79.3,"11,885",13.1,35%,39 : 61,2011
20,21,University of Hong Kong,Hong Kong,68.4,91.4,71.4,96.1,56.5,79.2,"19,835",17.6,38%,53:47:00,2011
21,22,University College London,United Kingdom,74.0,90.8,81.6,80.6,39,78.4,"26,607",10.7,46%,56:44:00,2011
22,23,University of Washington,United States of America,68.2,49,77.1,95.9,32.8,78,"44,020",11.8,13%,53:47:00,2011
23,24,Duke University,United States of America,66.8,49.4,71.5,92.3,100,76.5,"15,172",4.8,17%,49:51:00,2011
24,25,Northwestern University,United States of America,64.5,60.5,68.8,95.3,-,75.9,"18,334",13.8,15%,48:52:00,2011
25,26,University of Tokyo,Japan,87.7,18.4,91.9,58.1,-,75.6,"26,199",5.7,10%,NaN,2011
26,27,Georgia Institute of Technology,United States of America,67.9,73.2,72.6,83.2,95.1,75.3,"19,967",20.1,26%,31 : 69,2011
27,28,Pohang University of Science and Technology,South Korea,69.5,32.6,62.5,96.5,100,75.1,"3,055",10.1,4%,0.888888889,2011
28,29,"University of California, Santa Barbara",United States of America,56.6,64.3,68.0,98.8,89.8,75,"22,020",27.3,11%,52:48:00,2011
29,30,University of British Columbia,Canada,65.1,93.3,74.8,80.3,42.6,73.8,"50,152",17.6,25%,54:46:00,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2573,601-800,University of Tehran,Iran,26.1,16.5,16.9,15.8,-,NaN,"53,802",27.0,1%,45:55:00,2016
2574,601-800,University of Texas at El Paso,United States of America,18.6,30.4,18.7,18.4,-,NaN,"19,123",29.0,7%,54:46:00,2016
2575,601-800,Texas Tech University,United States of America,27.9,36.8,17.2,22.0,-,NaN,"29,512",20.9,7%,46:54:00,2016
2576,601-800,Tokai University,Japan,17.9,19.3,7.6,15.3,34.4,NaN,"29,700",12.7,1%,27 : 73,2016
2577,601-800,Tokushima University,Japan,25.3,16.8,21.6,12.8,59.6,NaN,"7,519",8.9,3%,34 : 66,2016
2578,601-800,Tokyo University of Marine Science and Technology,Japan,27.9,24.5,12.4,7.7,57.9,NaN,"2,597",11.1,7%,34 : 66,2016
2579,601-800,Tokyo University of Science,Japan,23.0,15.4,24.1,21.4,37.6,NaN,"20,243",25.7,2%,0.888888889,2016
2580,601-800,Tomsk State University,Russian Federation,34.8,36.9,20.8,7.6,44,NaN,"10,413",9.9,12%,60:40:00,2016
2581,601-800,Tottori University,Japan,24.3,16.7,10.1,9.6,34.5,NaN,"6,248",8.2,2%,34 : 66,2016
2582,601-800,Toyohashi University of Technology,Japan,22.0,25.4,18.9,15.8,50.3,NaN,"2,153",9.3,9%,0.438194444,2016
2583,601-800,Universiti Kebangsaan Malaysia,Malaysia,24.3,29.7,15.9,10.9,28.4,NaN,"24,227",11.8,12%,62:38:00,2016
2584,601-800,Universiti Putra Malaysia,Malaysia,25.3,50.1,20.9,10.2,34.2,NaN,"23,883",12.2,16%,63:37:00,2016
2585,601-800,Universiti Sains Malaysia,Malaysia,26.9,44.2,16.6,12.4,34.4,NaN,"28,179",14.8,10%,61:39:00,2016
2586,601-800,Universiti Teknologi MARA,Malaysia,15.2,14.8,7.7,18.2,28.3,NaN,"69,268",16.8,0%,65:35:00,2016
2587,601-800,Ural Federal University,Russian Federation,24.8,17.3,10.6,16.8,35.6,NaN,"28,427",10.1,3%,48:52:00,2016
2588,601-800,V.N. Karazin Kharkiv National University,Ukraine,21.7,48.4,8.9,1.7,28.8,NaN,"14,410",9.7,22%,53:47:00,2016
2589,601-800,University of Vigo,Spain,18.4,30.7,10.5,31.8,38.1,NaN,"22,793",19.0,3%,51:49:00,2016
2590,601-800,Vilnius University,Lithuania,18.3,40.8,13.6,26.1,41,NaN,"19,019",14.2,4%,65:35:00,2016
2591,601-800,Warsaw University of Technology,Poland,19.4,20.7,8.5,40.3,47.4,NaN,"34,572",14.5,3%,34 : 66,2016
2592,601-800,Waseda University,Japan,23.6,29.7,14.6,29.4,32.4,NaN,"52,316",16.9,8%,35 : 65,2016
2593,601-800,University of West Bohemia,Czech Republic,16.3,23.1,9.7,29.8,32.1,NaN,"15,639",21.5,2%,52:48:00,2016
2594,601-800,University of the West of England,United Kingdom,16.9,48.5,11.2,34.6,28.5,NaN,"22,525",21.4,15%,53:47:00,2016
2595,601-800,West University of Timi_oara,Romania,16.1,21,3.9,22.4,-,NaN,"12,933",19.0,3%,62:38:00,2016
2596,601-800,University of Westminster,United Kingdom,17.3,81.9,11.7,21.1,28.5,NaN,"16,609",21.0,43%,57:43:00,2016
2597,601-800,Xidian University,China,17.9,12.8,12.1,8.9,83.7,NaN,"31,618",16.4,2%,29 : 71,2016
2598,601-800,Yeungnam University,South Korea,18.6,24.3,10.9,26.5,35.4,NaN,"21,958",15.3,3%,48:52:00,2016
2599,601-800,Y�ld�z Technical University,Turkey,14.5,14.9,7.6,19.3,44,NaN,"31,268",28.7,2%,36 : 64,2016
2600,601-800,Yokohama City University,Japan,24.0,16.1,10.2,36.4,37.9,NaN,"4,122",3.7,3%,NaN,2016
2601,601-800,Yokohama National University,Japan,20.1,23.3,16.0,13.5,40.4,NaN,"10,117",12.1,8%,28 : 72,2016
2602,601-800,Yuan Ze University,Taiwan,16.2,17.7,18.3,28.6,39.8,NaN,"8,663",20.6,4%,43:57:00,2016

In [19]:
import pandas as pd
import numpy as np
## Load the data into a DataFrame
df = pd.read_csv('datasets/challenge-dataset.csv')

def change_to_float(inpt, replace):
    if type(inpt) == float:
        return inpt
    else:
        return inpt.replace(replace,'')

df['international'] = df['international'].replace('-',np.nan).astype(float)
df['income'] = df['income'].replace('-',np.nan).astype(float)
df['total_score'] = df['total_score'].replace('-',np.nan).astype(float)
df['num_students'] = df['num_students'].apply(lambda x: change_to_float(x,',')).astype(float)
df['international_students'] = df['international_students'].apply(lambda x: change_to_float(x,'%')).astype(float)

del df['female_male_ratio']

In [ ]:
df = pd.DataFrame({
  'y': np.random.randn(20),
  'x1': np.random.randn(20), 
  'x2': np.random.randn(20),
  'grp': ['a', 'b'] * 10})

def ols_res(x, y):
    return pd.Series(sm.OLS(y, x).fit().predict())

df.groupby('grp').apply(lambda x : x[['x1', 'x2']].apply(ols_res, y=x['y']))

In [ ]:
World_rank = []
score{woorld _cran} = score.index()